#!/dis/sh
load std

#echo cresh/pare $1$2
crindent = $1
#echo cresh/pare: $2
cresh/do $2

# doesn't print output of redoing dependent targets
#log = /tmp/$2.log.${pid}
#cresh/do $2 >> $log >[2=1]
#cat $log
#rm -f $log
