#!/dis/sh
load std

scriptdir = /lib/do/credo
if {no $*} {
	apply {
		script = $1
		group = `{echo $script | sed 's,(.*)\.(.*)\.(.*)\.(.*),\2,'}
		echo cresh/rm $group '	#' `{grep '(rm|cresh/rm)' $script | sed 's,cresh/rm ,,'}
	} `{ls $scriptdir/rm*}
	exit 0
}

apply {
	group = $1
	script = $scriptdir/rm-f.$group..do
	if {ftest -x $script} {sh $script}
} $*

exit 0
