#!/dis/sh
load std

if {no $srcdir} {
	srcdir = ''
	ossrcdir = ''
} {
	srcdir = `{echo $srcdir | sed 's,([^/])$,\1/,'}
	ossrcdir = `{osdir $srcdir}
}
echo srcdir $srcdir
echo ossrcdir $ossrcdir

if {no $*} {cre/lsdo; exit}

cretop = `{pwd}

apply {
	cd $cretop

	cretarget = $1
	if {~ $cretarget '*/*'} {
		dir = `{echo $cretarget | sed 's,(.*/)([^/]+)$,\1,'}
		if {~ $dir '/*'} {srcdir = $dir} {srcdir = $srcdir^$dir^'/'}
		ossrcdir = `{osdir $srcdir}
		cd $dir
		
		if {or {~ `{pwd}^'/' '*/'^$dir} {~ `{pwd}^'/' '*'^$dir}} {
			cretarget = `{echo $cretarget | sed 's,(.*/)([^/]+)$,\2,'}
		} {
			exit
		}
	}
	
	osdir = `{osdir}
	cre/doer $cretarget
} $*
