#!/dis/sh
load std

cd /lib/do
apply {
	dofile = $1
	(smith cmd in out) = `{echo $dofile | sed 's,\.do$,,;s,[.\/], ,g'}
	if {no $out} {out = ''''''}
	echo cre/catdo '('$smith $cmd $in $out')'
} `{ls */*.do | grep -v '\.dep\.do'}
