#!/dis/sh
load std

deps = `{ls *.dep >[2]/dev/null}
if {no $deps} {exit 0}
apply {
	f = $1
	ext = `{echo $f | sed 's,.*\.,,'}
	if {and {! ftest -e $f.do} {! ftest -e default.$ext.do} {! ftest -e $f.tr} {ftest -e $f}} {echo $f}
} `{cat $deps | sed 's,^.*[ 	],,' | grep -v '^/env/' | sort | uniq}
exit 0
