#!/dis/sh
load std

(name params) = $*
if {no $name} {
	ls *.test >[2]/dev/null | sed 's,\.test$,,'
	exit 0
}

test = $name.test
out = $name.test.out
past = $name.test.past
sh = $name.test.sh

sed -n 's,^	> ,,p' $test > $sh
if {ftest -e $out} {mv $out $past}

sh $sh $params >$out >[2=1]
status_sh = $status
if {! ~ $status_sh ''} {
	echo pastout: test $name returned $status_sh
	status_test = 'test error'
}

if {! ftest -e $past} {touch $past}
echo diff $past $out
diff $past $out

status $status_test
