#!/dis/sh
field2sed = 's,^.*[ 	],,'

olddepsum = `{cat $cretarget^.dep.sum >[2]/dev/null | sed $field1sed}

crevars = `{sed $field2sed $cretarget^.dep | sed -n 's,^\/env\/,,p'}
apply {
	crevar = $1
	if {ftest -r $cretarget.$crevar.env} {
		run $cretarget.$crevar.env
		echo $cretarget $crevar '=' $$crevar
		# Use these in ports where no /env,
		# or if we care why /env/$crevar changed.
		#rmdep $cretarget $crevar.env
		#adddep $cretarget $cretarget.$crevar.env
	} {
		if {ftest -r default.$crevar.env} {
			run default.$crevar.env
			echo default $crevar '=' $$crevar
			#rmdep $cretarget $crevar.env
			#adddep $cretarget default.$crevar.env
		}
	}
} $crevars

credepfiles = `{sed $field2sed $cretarget^.dep | sed '/^'^$cretarget^'$/d' | sed '/^\/env\//d'}
if {! no $credepfiles} {
	#echo credeper: map crepare $credepfiles
	map 'crepare ''  '^$crindent^''''  $credepfiles
}

credeps = `{sed $field2sed $cretarget^.dep}
apply {
	credep = $1
	crelay = $credep^.relay
	if {ftest -e $crelay} {run $crelay $credep}
} $credeps
apply {
	if {! md5sum $1 >[2]/dev/null} {
		echo '0	'^$1
		if {! ~ $1 '/env/*'} {nulltargetforce = 1}
	}
} $credeps > $cretarget^.dep.new

mv $cretarget^.dep.new $cretarget^.dep
(newdepsum newdepfile) = `{cresum $cretarget^.dep}
if {! ~ $#newdepsum 0} {echo $newdepsum^'	'^$newdepfile > $cretarget^.dep.sum}
