#!/dis/sh
if {~ $#* '[0123]'} {lscatdo; exit}
(smith cmd in out targets) = $*
if {no $targets} {targets = $cmd.$in.$out}
apply {
	target = $1
	prod = /lib/do/$smith/$cmd.$in.$out
	if {ftest -r $prod^.do} {catdo $smith $cmd $in $out > $target.do}
	if {ftest -r $prod^.dep} {catdep $smith $cmd $in $out | sh /dis/target $target > $target.dep}
	if {ftest -r $prod^.dep.do} {cp $prod.dep.do $target.dep.do}
	echo credo $target
} $targets

