#!/dis/sh
load std

if {~ $#* '[012]'} {
	lscatenv
	exit
}

libenvroot = /lib/env
(target localvar smith libvar qual) = $*
if {no $qual} {qual = ''} {qual = `{echo $qual | sed 's, ,.,g;s,^,.,'}}
libenvpath = $libenvroot/$smith/$libvar$qual.env
cat $libenvpath >> $target.$localvar.env
