#!/dis/sh
if {~ $#* '[012]'} {
	lscatenv
	exit
}

libenvroot = /lib/env
(localvar smith var qual) = $*
qual = `{echo $qual | sed 's, ,.,g'}
libvar = $libenvroot/$smith/$var.$qual.env
cat $libvar >> $localvar.env
