#!/dis/sh
load std

targets = $*
if {no $targets} {
	deps = `{ls *.dep >[2]/dev/null}
} {
	deps = `{apply {ls $1.dep >[2]/dev/null} $targets}
}
if {no $deps} {exit 0}
apply {
	f = $1
	if {! ftest -e $f.do} {echo $f | sed 's,^/env/,,'}
} `{cat $deps | sed 's,^.*[ 	],,' | grep '^/env/' | sort | uniq}
exit 0
