#!/dis/sh
deps = `{ls *.dep >[2]/dev/null}
if {no $deps} {exit 0}
apply {
	f = $1
	if {! ftest -e $f.do} {echo $f | sed 's,^/env/,,'}
} `{cat $deps | sed 's,^.*[ 	],,' | grep '^/env/' | sort | uniq}
exit 0
