#!/dis/sh
load std

flag x +

names = $*
if {no $names} {
	names = `{apply {sfix %.test % $1} *.test}
}
apply {
	name = $1
	out = $name.test.out
	past = $name.test.past
	sh = $name.test.sh

	sed -n 's,^	> ,,p' $name.test > $sh
	if {ftest -e $out} {mv $out $past}

	cat $sh
	sh $sh >$out >[2=1]
	status_sh = $status
	if {! ~ $status ''} {
		echo pastout: test $name returned $status_sh
		status_test = 'test error'
	}

	if {! ftest -e $past} {touch $past}
	flag x +
	diff $past $out
} $names

status $status_test
