#!/dis/sh
tests = $*
if {no $tests} {
	tests = *.test
} {
	tests = `{echo $tests | fmt -w 1 | sed 's,$,.test,'}
}
apply {
	test = $1
	sed -n 's,^	> ,,p' $test > $test.sh
	if {ftest -e $test.out} {mv $test.out $test.past}
	sh $test.sh > $test.out >[2=1]
	if {! ftest -e $test.past} {touch $test.past}
	flag x +
	diff $test.past $test.out
} $tests
