#!/dis/sh
load std

names = $*
if {no $names} {
	names = `{apply {sfix %.test % $1} *.test}
}
apply {
	name = $1
	if {! ftest -d $name} {mkdir -p $name}
	out = $name/$name.test.out
	past = $name/$name.test.past
	sh = $name/$name.test.sh

	sed -n 's,^	> ,,p' $name.test > $sh
	if {ftest -e $out} {mv $out $past}
	cre/in $name sh $sh > $out >[2=1]
	if {! ftest -e $past} {touch $past}
	flag x +
	diff $past $out
} $names
